# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ebcad99f2496eb97dd3c8c4393acfe4f5f5ce7534b932bc83c77bd2d30f3e5e418cf67d1bc0ac45b76de49289807ce52ae3528bebab25b0fca03032e06a8c211

test:
  secret_key_base: 264c1f9a33f533a31a7061023a4f8f1f96f9b72823b8998c9c55cb854d50870305e55d4e9716fc9315b21b5569747b3b9b957679e05a65f8f2ca00baf423e540

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
